add links to refistration, login and logout
paul-reed-smith/task-manager pull request #12
Opened 2021-04-27 09:37 UTC by paul-reed-smith

2021-04-27 16:54 UTC, greybutton requested changes

2021-04-27 16:54 UTC, greybutton commented on db/migrate/20210419150823_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
почему миграции удалил? они нужны как бы, верни их плис

2021-04-27 17:04 UTC, paul-reed-smith commented on db/migrate/20210419150823_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
Там ошибка была с миграциями.

2021-04-27 17:34 UTC, paul-reed-smith commented on db/migrate/20210419150823_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
Поправил ошибку

2021-04-27 18:43 UTC, greybutton commented on db/migrate/20210419150823_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
в чем ошибка была с миграциями?

2021-04-27 18:43 UTC, greybutton approved these changes

2021-04-27 18:56 UTC, paul-reed-smith commented on db/migrate/20210419150823_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
При запуске : "Migrations are pending. To resolve this issue, run: bin/rails db:migrate RAILS_ENV=development"
А при попытке запуска этой команды: "PG::DuplicateTable: ERROR:  relation "users" already exists"
Решил с помощью: rails db:migrate:reset

2021-04-27 19:08 UTC, merged

2021-04-28 06:00 UTC, greybutton commented on db/migrate/20210419150823_create_users.rb
> -class CreateUsers < ActiveRecord::Migration[6.1]
ок